version: '3.8'
services:
  chargepoint:
    build: .
    image: chargepoint-mqtt
    restart: unless-stopped
    environment:
      STATIONS: ""
      MQTT_HOST: ""
      MQTT_PORT: "1883"
      MQTT_USER: ""
      MQTT_PASS: ""
      MQTT_PREFIX: "homeassistant"
      INTERVAL: "60"
      ONCE: "0"